#!/bin/bash
read -p 'IP to look for: ' ip
if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
then
  echo This is a valid ip address format: $ip 
else 
  echo This is not an IP address
  exit 1
fi
if grep -Fq $ip  addrules
	then
	    echo IP already exist in addrules
#	    iptables -L -n |grep $ip
	    rules=`iptables-save |grep $ip`
	    echo The current matching rule is this: $rules
	    echo
#	    head -15 addrules
#	    num=`iptables -L -n |wc -l`
#	    echo There are $num of rules in iptables
	    var=`cat addrules|wc -l`
    	    var1=7
	    echo There are $((var-var1)) active rules in the firewall
	    count=`cat count`
#	    echo $count
	    last=`cat last`
	    echo There are $((last - $count)) new rules added since the last sort
	    echo These are all the new rules added since last sort
	    awk 'NR >= '$count' && NR <= '$((last - 1))'' addrules
	    # code if found
	else
	    echo But it does not exist in the firewall yet, it needs to be added to addrules
	    echo "**********************************************************************************"
	    echo " This ip address $ip has now been banned from accessing this system...  "
	    echo "**********************************************************************************"
	    sed -i "/^iptables -A INPUT -j LOG/a iptables -A INPUT -s $ip/32 -p tcp -j DROP" addrules
	    ./addrules
	    rule=`iptables -L -n |grep $ip`
	    echo
	    echo The new rule is now active as $rule
#	    head -15 addrules
#	num=`iptables -L -n |wc -l`
#       echo There are $num of rules in iptables
#	    var=`cat addrules|wc -l`
#            var1=7
#            echo There are $((var-var1)) active rules in the firewall
	    count=4
#	    echo $count
	    last=`cat last`
	    echo There are $((last - $count)) rule addidions since the last update:
	    echo $((last + 1)) >last
	    last =`cat last`
#	    echo $last
	    lines=`cat addrules |wc -l`
	    num=$((lines - 7))
	    echo There are $num of rules in iptables
	    echo There are $((last - 4)) rule addidions since the last update:
	    echo Here are the last $((last - 4)) rules
	    awk 'NR >= '$((count + 1))' && NR <= '$last'' addrules
#	    echo Updated last count to $last
	    # code if not found
fi
echo done
