#!/bin/bash
read -p 'IP to look for: ' ip
echo
echo Var is $ip
if grep -Fq $ip addrules
then
    echo IP already exist in addrules
    rule=`iptables -L -n |grep $ip`
    echo This ip is active in this rule $rule
    echo
    echo
    num=`iptables -L -n |wc -l`
    echo There are $num lines in iptables
    # code if found
else
    echo Does not exist, IP addres needs to be added to addrules
    echo Use banip.sh to ban the ip from accessing system
#    sed -i "/^iptables -A INPUT -j LOG/a iptables -A INPUT -s $ipaddr/32 -p tcp -j DROP" addrules
#    ./addrules
#    iptables -L -n |grep $ip 
    echo
    echo
    num=`iptables -L -n |wc -l`
    echo There are $num lines in iptables
    # code if not found
fi
echo
echo done

