#!/bin/bash
read -p 'IP to look for: ' ip
echo Var is $ip
if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] 
then
  echo This is a valid ip, $ip
  echo IP already exist in addrules
    rule=`iptables -L -n |grep $ip`
    echo This ip is already associated with an active firewall rule
    echo This is what the rule looks like: $rule
#    head -15 addrules
    echo
#    num=`iptables -L -n |wc -l`
#    echo There are $num lines in iptables
    var=`cat addrules|wc -l`
    var1=7
    echo There are $((var-var1)) active rules in the firewall
    count=`cat count`
    echo $count
    last=`cat last`
    echo $last
    echo There have been $((last - $count)) rule addidions since the last update:
    echo Here are the last $((last - $count)) rules
    awk 'NR >= '$count' && NR <= '$((last - 1))'' addrules
    # code if found
elif
    echo This is a valid but it does not exist as an active firewall rule yet 
    echo This IP address should be added to addrules
    echo Use banip.sh to block the ip from accessing this system
    echo
    var=`cat addrules|wc -l`
    var1=7
    echo There are $((var-var1)) active rules in the firewall
    count=`cat count`
    echo $count
    last=`cat last`
    echo $last
    echo There have been $((last - $count)) rule addidions since the last update:
    echo Here are the last $((last - $count)) rules
    awk 'NR >= '$count' && NR <= '$((last - 1))'' addrules
    # code if not found
then 
    echo This is not an IP address
fi
echo
echo done

